#baseURL = 'https://hfx.bike/'
baseURL = 'https://cgeroux.github.io/hfxdotbike/'
languageCode = 'en-us'
title = 'hfx.bike'
theme = "ananke"

[menu]
[[menu.main]]
name = "@BikeMayorHfx"
url = "https://twitter.com/BikeMayorHfx"
weight = 10
[[menu.main]]
name = "@BikeHfxStats"
url = "https://twitter.com/BikeHfxStats"
weight = 9
[[menu.main]]
name = "Kidical Mass"
url = "./kidical-mass/"
weight = 8

[params.kidicalmass]
email="KidicalMassHfx@gmail.com"
#twitter=""
#instagram=""
facebook="https://www.facebook.com/profile.php?id=100089191422241"
header_img="/kidical-mass/img/banner-1024x448.jpg"
[[params.kidicalmass.menu]]
name="calendar"
url="kidical-mass/calendar"
[[params.kidicalmass.menu]]
name="more"
url="kidical-mass/more"
#[[params.kidicalmass.menu]]
#name="reminders"
#url="kidical-mass/reminders"

